version: '3.8'

services:

  tailscale:
    build:
      context: .
    user: root
    ports:
      - "${PORT:-1055}:${PORT:-1055}"
    environment:
      - PORT=${PORT}
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_SOCKS5_SERVER=0.0.0.0:${PORT}
    volumes:
      - tailscale_data:/var/lib/tailscale
    restart: unless-stopped
    
volumes: 
  tailscale_data:
