version: '3.8'

services:

  tailscale:
    image: tailscale/tailscale:latest
    user: root
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_SOCKS5_SERVER=0.0.0.0:1055
    volumes:
      - tailscale_data:/var/lib/tailscale
    restart: unless-stopped
    
volumes: 
  tailscale_data:
