version: '3.8'

services:

  tailscale:
    image: tailscale/tailscale:latest
    user: root
    environment:
      # Autorización
      - TS_AUTHKEY=${TS_AUTHKEY}
      # Las rutas mágicas de Tailscale para Docker
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      # EL TRUCO ESTÁ AQUÍ: Le pedimos que abra un proxy SOCKS5 interno
      - TS_SOCKS5_SERVER=0.0.0.0:1055
    # Para que funcione dentro de Docker sin privilegios extraños
    volumes:
      - tailscale_data:/var/lib/tailscale
    restart: unless-stopped
    
  prometheus:
    build:
      context: ./prometheus
      dockerfile: dockerfile
    user: root # required for data persistence
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  loki:
    build:
      context: ./loki
      dockerfile: dockerfile
    user: root # required for data persistence
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki

  tempo: 
    build:
      context: ./tempo
      dockerfile: dockerfile
    user: root # required for data persistence
    ports:
      - "3200:3200" # http server for querying
      - "4317:4317" # grpc server for ingest
      - "4318:4318" # http server for ingest
    volumes:
      - tempo_data:/var/tempo

  grafana:
    build:
      context: ./grafana
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword123
      - GF_DEFAULT_INSTANCE_NAME=Grafana
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel
      - LOKI_INTERNAL_URL=http://loki:3100
      - PROMETHEUS_INTERNAL_URL=http://prometheus:9090
      - TEMPO_INTERNAL_URL=http://tempo:3200
  
  example_api: 
    build:
      context: ./examples/api
      dockerfile: dockerfile
    ports:
      - "9091:9091"
    environment:
      - TEMPO_URL=http://tempo:4318
      - TEMPO_SERVICE_NAME=example_api

volumes: 
  prometheus_data:
  loki_data:
  grafana_data:
  tempo_data:
