FROM alpine:latest
ARG VERSION=v3.2.1

RUN apk add --no-cache prometheus tailscale

COPY prom.yml /etc/prometheus/prom.yml

# Preparamos el directorio de datos para evitar errores de permisos
RUN mkdir -p /prometheus && chmod 777 /prometheus

# Cambiamos la estrategia del script
RUN echo '#!/bin/sh' > /start.sh && \
    echo 'tailscaled --tun=userspace-networking --socks5-server=localhost:1055 & \
          (sleep 3 && if [ -n "$TS_AUTHKEY" ]; then tailscale up --authkey=$TS_AUTHKEY; fi) & \
          exec prometheus --config.file=/etc/prometheus/prom.yml --storage.tsdb.path=/prometheus --web.enable-lifecycle' > /start.sh && \
    chmod +x /start.sh

EXPOSE 9090

ENTRYPOINT ["/start.sh"]
