global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  # --- PROMETHEUS (Auto-monitoreo) ---
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # --- EXTERNAL API — PRODUCCIÓN ---
  - job_name: 'external-api-prod'
    scheme: http
    # opcional: proxy si tu red lo requiere
    # proxy_url: http://127.0.0.1:1055
    static_configs:
      - targets: ['external-api-production-3af3.up.railway.app:80']
        labels:
          env: 'prod'

  # --- EXTERNAL API — DESARROLLO (TAILSCALE) ---
  - job_name: 'external-api-dev'
    scheme: http
    proxy_url: http://tailscale-proxy.railway.internal:1055
    static_configs:
      - targets: ['100.117.194.110:8000']
        labels:
          env: 'dev'

  # --- N8N — PRODUCCIÓN ---
  - job_name: 'n8n-prod'
    scheme: http
    static_configs:
      - targets: ['primary-production-cfef6.up.railway.app:80']
        labels:
          env: 'prod'

  # --- N8N — DESARROLLO (TAILSCALE) ---
  - job_name: 'n8n-dev'
    scheme: http
    proxy_url: http://tailscale-proxy.railway.internal:1055
    static_configs:
      - targets: ['100.117.194.110:5678']
        labels:
          env: 'dev'

  # --- ANALYTICS API — PRODUCCIÓN ---
  - job_name: 'analytics-api-prod'
    scheme: http
    static_configs:
      - targets: ['analytics-api-production-1326.up.railway.app:80']
        labels:
          env: 'prod'

  # --- ANALYTICS API — DESARROLLO (TAILSCALE) ---
  - job_name: 'analytics-api-dev'
    scheme: http
    proxy_url: http://tailscale-proxy.railway.internal:1055
    static_configs:
      - targets: ['100.117.194.110:2222']
        labels:
          env: 'dev'
  
  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE
