global:
  scrape_interval: 10s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'external-api'
    scheme: http
    static_configs:
      - targets: ['external-api-production-3af3.up.railway.app']
        labels:
          env: 'production'

  - job_name: 'n8n'
    scheme: http
    static_configs:
      - targets: ['primary-production-cfef6.up.railway.app']
        labels:
          env: 'production'

  - job_name: 'analytics-api'
    scheme: http
    static_configs:
      - targets: ['analytics-api-production-1326.up.railway.app']
        labels:
          env: 'production'

  - job_name: 'external-api'
    scheme: http
    static_configs:
      - targets: ['100.117.194.110:8000']
        labels:
          env: 'development'

  - job_name: 'n8n'
    scheme: http
    static_configs:
      - targets: ['100.117.194.110:5678']
        labels:
          env: 'development'
  
  - job_name: 'analytics-api'
    scheme: http
    static_configs:
      - targets: ['100.117.194.110:2222']
        labels:
          env: 'development'
  
  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE
